from . import common
from . import test_change_request_type
from . import test_change_request
from . import test_apply_strategies
from . import test_add_member_strategy
from . import test_dms_directory_creation
from . import test_document_upload_wizard
from . import test_workflow_integration
from . import test_remove_member_strategy
from . import test_change_hoh_strategy
from . import test_exit_registrant_strategy
from . import test_transfer_member_strategy
from . import test_update_id_strategy
from . import test_create_group_strategy
from . import test_merge_registrants_strategy
from . import test_split_household_strategy
from . import test_e2e_workflows
from . import test_conflict_detection
from . import test_conflict_detection_extended
from . import test_approval_per_cr_type
from . import test_ux_wizards
from . import test_stage_navigation
from . import test_approval_hooks_and_audit
from . import test_dynamic_approval
from . import test_conflict_dynamic_approval
from . import test_html_escaping
from . import test_wizard_html_escaping
from . import test_cr_roles_registry_scope
