from . import test_locale_providers
from . import test_demo_data_generator
from . import test_res_config_settings
from . import test_res_country
from . import test_res_partner
from . import test_apps_wizard
from . import test_demo_stories
from . import test_demo_area_loader
from . import test_demo_user_safety
