{  # pylint: disable=pointless-statement
    "name": "OpenSPP DCI Server",
    "summary": "DCI API server infrastructure with FastAPI routers",
    "version": "19.0.2.0.4",
    "category": "OpenSPP/Integration",
    "author": "OpenSPP.org",
    "website": "https://github.com/OpenSPP/OpenSPP2",
    "license": "LGPL-3",
    "development_status": "Alpha",
    "depends": [
        "base",
        "fastapi",
        "job_worker",
        "spp_dci",
        "spp_dci_client",
        "spp_api_v2",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/fastapi_endpoint_data.xml",
        "data/queue_limit_data.xml",
        "data/cron_data.xml",
        "data/server_key_default.xml",
        "views/sender_registry_views.xml",
        "views/transaction_views.xml",
        "views/subscription_views.xml",
        "views/res_config_settings_views.xml",
    ],
    "installable": True,
    "application": False,
    "maintainers": ["jeremi", "gonzalesedwin1123"],
}
