# pylint: disable=pointless-statement
# Part of OpenSPP. See LICENSE file for full copyright and licensing details.
{
    "name": "OpenSPP Programs",
    "summary": "Manage programs, cycles, beneficiary enrollment, entitlements (cash and in-kind), payments, and fund tracking for social protection.",
    "category": "OpenSPP/Core",
    "version": "19.0.2.2.2",
    "sequence": 1,
    "author": "OpenSPP.org",
    "website": "https://github.com/OpenSPP/OpenSPP2",
    "license": "LGPL-3",
    "development_status": "Production/Stable",
    "maintainers": ["jeremi", "gonzalesedwin1123", "reichie020212"],
    "depends": [
        "account",
        "web",
        "base",
        "mail",
        "spp_registry",
        "spp_banking",
        "calendar",
        "product",
        "stock",
        "spp_security",
        "spp_area",
        "spp_service_points",
        "spp_user_roles",
        "spp_base_common",
        "spp_approval",
        "spp_hazard",
        "spp_gis_report",
        # CEL core libraries for expression-based managers
        "spp_cel_domain",
        "spp_cel_widget",
        "job_worker",
    ],
    "data": [
        # Security files (merged from both modules)
        "security/privileges.xml",
        "security/groups.xml",
        "security/program_security.xml",
        "security/ir.model.access.csv",
        "security/registrant_rule.xml",
        "security/area_filter_rules.xml",
        # Data files
        "data/sequences.xml",
        "data/queue_data.xml",
        "data/user_roles.xml",
        "data/approval_definitions.xml",
        "data/cel_examples.xml",
        "data/eligibility_expression_templates.xml",
        # Reports
        "report/voucher_card.xml",
        "report/report_format.xml",
        "report/summary_report.xml",
        "report/program_approval_receipt.xml",
        # Main views
        "views/main_view.xml",
        "views/programs_view.xml",
        "views/program_config_cards_view.xml",
        "views/program_membership_view.xml",
        "views/cycle_view.xml",
        "views/cycle_membership_view.xml",
        "views/entitlement_view.xml",
        "views/entitlement_cash_view.xml",
        "views/payment_view.xml",
        "views/payment_batch_view.xml",
        "views/payment_batch_tag_view.xml",
        "views/registrant_view.xml",
        "views/inkind_entitlement_report_view.xml",
        "views/spp_entitlement_view.xml",
        # Compliance views
        "views/cycle_compliance_view.xml",
        "views/program_compliance_view.xml",
        "views/res_config_settings_compliance_view.xml",
        "views/cycle_membership_compliance_view.xml",
        # Manager views (must load before CEL views since CEL inherits from them)
        "views/managers/eligibility_manager_view.xml",
        "views/managers/deduplication_manager_view.xml",
        "views/managers/notification_manager_view.xml",
        "views/managers/program_manager_view.xml",
        "views/managers/cycle_manager_view.xml",
        "views/managers/entitlement_manager_view.xml",
        "views/managers/entitlement_manager_cash_view.xml",
        "views/managers/entitlement_manager_inkind_view.xml",
        "views/managers/payment_manager_view.xml",
        # CEL views (inherit from manager views, must load after)
        "views/cel/cel_help_templates.xml",
        "views/cel/cel_builder_wizard_views.xml",
        "views/cel/eligibility_cel_views.xml",
        "views/cel/entitlement_amount_cel_views.xml",
        "views/cel/entitlement_condition_cel_views.xml",
        "views/cel/entitlement_inkind_cel_views.xml",
        # NOTE: compliance_cel_views.xml removed - compliance now handled by program_compliance_view.xml
        # Accounting views
        "views/accounting/fund_management_view.xml",
        "views/accounting/account_journal_view.xml",
        "views/accounting/fund_report_view.xml",
        "views/accounting/account_journal_config_view.xml",
        # Other views
        "views/duplicate_view.xml",
        # Wizards
        "wizard/assign_to_program_wizard.xml",
        "wizard/multi_entitlement_approval_wizard.xml",
        "wizard/create_program_wizard.xml",
        "wizard/assign_payments_batch_wizard.xml",
        "wizard/inkind_entitlement_report_wiz.xml",
        "wizard/multi_inkind_entitlement_approval_wizard.xml",
        "wizard/reject_entitlement_wizard.xml",
        "wizard/reject_inkind_entitlement_wizard.xml",
        "wizard/reset_to_pending_wizard.xml",
        "wizard/create_program_wizard_compliance_views.xml",
        "wizard/create_program_wizard_cel_views.xml",
        "wizard/enrollment_wizard_views.xml",
        "wizard/exit_membership_wizard.xml",
        "wizard/prepare_entitlement_confirm_wizard.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "spp_programs/static/src/css/cel_builder_wizard.css",
            "spp_programs/static/src/js/domain_field.js",
            "spp_programs/static/src/js/custom_open_list.js",
            "spp_programs/static/src/js/create_program.js",
            "spp_programs/static/src/js/field_domain.js",
            "spp_programs/static/src/js/cel_builder_wizard.js",
            "spp_programs/static/src/js/form_controller_create.js",
            "spp_programs/static/src/css/style.css",
            "spp_programs/static/src/xml/create_program_template.xml",
            "spp_programs/static/src/xml/field_domain.xml",
        ],
    },
    "demo": [],
    "images": [],
    "external_dependencies": {
        "python": [
            "python-dateutil",
        ]
    },
    "application": True,
    "installable": True,
    "auto_install": False,
}
