{
    "name": "OpenSPP API V2",
    "category": "OpenSPP/Integration",
    "version": "19.0.2.1.0",
    "sequence": 1,
    "author": "OpenSPP.org",
    "website": "https://github.com/OpenSPP/OpenSPP2",
    "license": "LGPL-3",
    "development_status": "Production/Stable",
    "maintainers": ["jeremi", "gonzalesedwin1123", "reichie020212", "emjay0921"],
    "external_dependencies": {
        "python": ["pyjwt"],
    },
    "depends": [
        "base",
        "fastapi",
        "spp_security",
        "spp_registry",
        "spp_consent",
        "spp_vocabulary",
        "spp_source_tracking",
    ],
    "data": [
        "security/privileges.xml",
        "security/groups.xml",
        "security/ir.model.access.csv",
        "data/config_data.xml",
        "data/fastapi_endpoint.xml",
        "data/api_path_data.xml",
        "data/filter_config_individual.xml",
        "data/filter_config_group.xml",
        "wizards/show_secret_wizard_views.xml",
        "views/api_client_views.xml",
        "views/api_extension_views.xml",
        "views/api_path_views.xml",
        "views/consent_views.xml",
        "views/api_outgoing_log_views.xml",
        "views/menu.xml",
    ],
    "assets": {},
    "demo": [],
    "images": [],
    "application": True,
    "installable": True,
    "auto_install": False,
    "post_init_hook": "_post_init_hook",
    "summary": """
        OpenSPP API V2 - Standards-aligned, consent-respecting API for social protection data exchange.
    """,
}
