# pylint: disable=pointless-statement
{
    "name": "OpenSPP Graduation Management",
    "summary": "Manage graduation and exit from time-bound social protection programs",
    "version": "19.0.2.0.2",
    "category": "OpenSPP",
    "author": "OpenSPP.org",
    "website": "https://github.com/OpenSPP/OpenSPP2",
    "license": "LGPL-3",
    "development_status": "Production/Stable",
    "maintainers": ["jeremi", "gonzalesedwin1123", "emjay0921"],
    "depends": [
        "base",
        "spp_registry",
        "spp_security",
        "mail",
    ],
    "external_dependencies": {"python": ["python-dateutil"]},
    "data": [
        "security/privileges.xml",
        "security/graduation_security.xml",
        "security/graduation_rules.xml",
        "security/ir.model.access.csv",
        "views/graduation_pathway_views.xml",
        "views/graduation_assessment_views.xml",
        "views/graduation_criteria_views.xml",
        "views/graduation_menus.xml",
        "data/graduation_data.xml",
    ],
    "demo": [],
    "installable": True,
    "application": False,
    "auto_install": False,
}
