{
    "name": "OpenSPP Change Request V2",
    "version": "19.0.3.0.0",
    "sequence": 50,
    "category": "OpenSPP",
    "summary": "Configuration-driven change request system with UX improvements, conflict detection and duplicate prevention",
    "author": "OpenSPP.org",
    "website": "https://github.com/OpenSPP/OpenSPP2",
    "license": "LGPL-3",
    "development_status": "Production/Stable",
    "depends": [
        "base",
        "mail",
        "spp_base_common",
        "spp_registry",
        "spp_area",
        "spp_gis",
        "spp_security",
        "spp_approval",
        "spp_event_data",
        "spp_hazard",
        "spp_dms",
        "spp_vocabulary",
    ],
    "data": [
        # Security
        "security/privileges.xml",
        "security/groups.xml",
        "security/rules.xml",
        "security/area_filter_rules.xml",
        "security/ir.model.access.csv",
        # Views (loaded before data that references them)
        "views/dms_file_views.xml",
        "views/change_request_type_views.xml",
        "views/change_request_views.xml",
        "views/stage_documents_form.xml",
        "views/stage_review_form.xml",
        "views/detail_add_member_views.xml",
        "views/detail_edit_individual_views.xml",
        "views/detail_edit_group_views.xml",
        "views/detail_remove_member_views.xml",
        "views/detail_change_hoh_views.xml",
        "views/detail_exit_registrant_views.xml",
        "views/detail_transfer_member_views.xml",
        "views/detail_update_id_views.xml",
        "views/detail_create_group_views.xml",
        "views/create_group_member_wizard_views.xml",
        "views/detail_merge_registrants_views.xml",
        "views/detail_split_household_gis_views.xml",
        "views/detail_split_household_views.xml",
        "views/preview_changes_wizard_views.xml",
        "views/document_upload_wizard_views.xml",
        "views/conflict_rule_views.xml",
        "views/conflict_wizard_views.xml",
        "views/conflict_extensions.xml",
        # UX Improvements
        "views/create_wizard_views.xml",
        "views/batch_approval_wizard_views.xml",
        "views/conflict_comparison_wizard_views.xml",
        "views/queue_views.xml",
        "views/menus.xml",
        # Data
        "data/dms_directories.xml",
        "data/sequences.xml",
        "data/event_types.xml",
        "data/user_roles.xml",
    ],
    "oca_data_manual": [
        "data/default_types.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "spp_change_request_v2/static/src/components/**/*",
            "spp_change_request_v2/static/src/css/cr_search_results.css",
            "spp_change_request_v2/static/src/js/create_change_request.js",
            "spp_change_request_v2/static/src/js/search_delay_field.js",
            "spp_change_request_v2/static/src/js/cr_search_results_field.js",
            "spp_change_request_v2/static/src/xml/create_change_request_template.xml",
            "spp_change_request_v2/static/src/xml/search_delay_field.xml",
            "spp_change_request_v2/static/src/xml/cr_search_results_field.xml",
            "spp_change_request_v2/static/src/js/cr_review_documents.js",
            "spp_change_request_v2/static/src/xml/cr_review_documents.xml",
        ],
    },
    "installable": True,
    "application": False,
    "auto_install": False,
    "maintainers": ["jeremi", "gonzalesedwin1123"],
}
